[workspace]
members = [
    "even-fibonacci-numbers",
    "largest-prime-factor",
    "even-fibonacci-numbers",
    "largest-palindrome-product",
    "largest-prime-factor",
    "multples-of-3-and-5",
    "perfection-quotients",        # still working on this one
    "smallest-multiple",
    "sum-square-difference",
    "xth-prime",
    "largest-product-in-a-series",
    "special-pythagorean-triplet",
    "summation-of-primes",
]
resolver = "2"

default-members = ["summation-of-primes"]
